// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93ZuqXw1MB94wCOgOPiwWY9Pzng-flcE',
    appId: '1:66340898524:web:7069b3b85995a92684d619',
    messagingSenderId: '66340898524',
    projectId: 'futsalapp-1c440',
    authDomain: 'futsalapp-1c440.firebaseapp.com',
    storageBucket: 'futsalapp-1c440.firebasestorage.app',
    measurementId: 'G-CBVCR81MN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQUdOUEl30uqyyhG8IHu462_61u7OCpA',
    appId: '1:66340898524:android:1976b349262e79f784d619',
    messagingSenderId: '66340898524',
    projectId: 'futsalapp-1c440',
    storageBucket: 'futsalapp-1c440.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA93ZuqXw1MB94wCOgOPiwWY9Pzng-flcE',
    appId: '1:66340898524:web:36e7a17aa5867fdb84d619',
    messagingSenderId: '66340898524',
    projectId: 'futsalapp-1c440',
    authDomain: 'futsalapp-1c440.firebaseapp.com',
    storageBucket: 'futsalapp-1c440.firebasestorage.app',
    measurementId: 'G-M7LSNHN9W7',
  );
}
